### ISSUE TITLE
Document how to run/use this project

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-sb1-converter#15]
There is currently no information in the README.md at all; it should be updated to include information describing what the project is and how to install/run/make use of it. Since this is is sort of a "library" made for Scratch 3.0, I think basing the README off of that of [scratch-svg-renderer](https://github.com/LLK/scratch-svg-renderer/#readme) would make sense (it's also effectively a library for 3.0).

**Comment by thisandagain** [comment]
We are aware. We are still working on documentation. This is what happens when we move to open source things quickly. ;-)
