### ISSUE TITLE
Can't select .sb files to upload from my computer

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-sb1-converter#4]
When I choose File>Upload from my computer, the .sb file I wanted to upload was grayed out.  I should be able to upload .sb files from my computer.
![screen shot 2018-12-04 at 2 49 48 pm](https://user-images.githubusercontent.com/1088291/49468958-3b9be500-f7d4-11e8-9a46-7040c6568c26.png)

Found on Chrome on Mac

**Comment by kchadha** [comment]
Note to self: this should be resolved in scratch-gui when the VM changes go in.
