### ISSUE TITLE
Loading a new sb1 over another sb1 the costumes are all from the first project

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-sb1-converter#6]
If you load an sb1 and then load a second sb1 in the same tab, all of the sprites for the second project will have the costumes and backdrop of the first project.

## Steps to Reproduce
Load project 115120
In the same tab load project 267801817
note: the project loads and there are the same number of sprites as the second project that have the same names.  Those sprites also have the same number of costumes.
HOWEVER:  all of the images are the same as the old project.

If you then reload the page from the url bar it appears as the second project as expected.

![sb1loadover](https://user-images.githubusercontent.com/1088291/49470609-8cadd800-f7d8-11e8-89c0-666ae7447237.gif)

Loading an sb1 over an sb2 or sb3 does not load the first project's costumes.  If you loaded an sb1, then an sb2 and then another sb1 will load the costumes from the first sb1!!

Found on Chrome on Mac

**Comment by kchadha** [comment]
~Note to self: this is happening because `vm.clear` is happening after the project `validates` but we are skipping validation in the case of sb1 projects.~

**Comment by kchadha** [comment]
@mzgoddard, any idea what's happening here? It seems like maybe the costumes in the fake zip are the old ones instead of new ones getting generated?

**Comment by kchadha** [comment]
Actually, I think this might have been resolved with #28. 

@BryceLTaylor, can you confirm that we can no longer repro this issue on develop?

**Comment by mzgoddard** [comment]
Oh that’d make sense the costume assets are being stored in scratch storage
by their md5. The fake md5s are stored in storage and then when the project
reads it uses the cached assets. Using real md5s the storage does not have
cached versions and so actually loads the new assets because they should
have new md5s

**Comment by kchadha** [comment]
@mzgoddard, oh right, that makes sense!

**Comment by BryceLTaylor** [comment]
This is fixed
